### ISSUE TITLE
App Autoscaling | ALBRequestCountPerTarget

### ISSUE THREAD

**Issue by ASVincent** [awsdocs/application-auto-scaling-user-guide#2]
I've looked through some of AWS's information on the app autoscaling functionality for ecs services and I can't find what period the ALBRequestCountPerTarget policy is evaluated for or if it relates to the scale up / scale down values.

If I author a target value of 600 is that 600 completed requests per 5 minute period, per 1 minute interval, per 1 hour interval?

I just can't find a period/interval to reason about what my target value should be.

Here is an example from the aws-cli about app scaling: https://github.com/aws/aws-cli/blob/13762544b5bc7c6bcf075ace753300b3547c20c8/awscli/examples/autoscaling/put-scaling-policy.rst

the docs linked to by cdk: https://docs.aws.amazon.com/autoscaling/application/APIReference/API_PredefinedMetricSpecification.html

Any assistance in finding what I've missed about this feature would be gladly appreciated

**Comment by Reneehi** [comment]
Hi,

Good question. I will put something in the Application Auto Scaling docs to make this information more available.

The place where you can see the metric frequency is here in the docs for Application Load Balancing: 
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-cloudwatch-metrics.html
"If there are requests flowing through the load balancer, Elastic Load Balancing measures and sends its metrics in 60-second intervals." 

Most metrics are published in 1-minute intervals.

I trust this is helpful.

Regards,
Renee

**Comment by Reneehi** [comment]
I will add to this to say that the ALBRequestCountPerTarget predefined metric (listed as RequestCountPerTarget in the link I shared) is always reported. Some of the metrics on that page are only reported if there are requests flowing through the load balancer,

**Comment by Reneehi** [comment]
Hello, 

Sorry for the delay in getting these updates finished.

Just a quick update that there is now a section for "Choosing metrics" in the Application Auto Scaling User Guide with information about the metric frequency (1 minute by default for most AWS metrics). https://docs.aws.amazon.com/autoscaling/application/userguide/application-auto-scaling-target-tracking.html#available-metrics

Thank you for your feedback. Hope this is helpful.

Renee
